apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- minio
- amq-broker-operator
- amq-broker
- influxdb
- battery-simulator
- data-ingester
- dashboard
- mqtt2ws
- influx-exporter