kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: minio

labels:
  - pairs:
      component: minio

resources:
- namespace.yaml
- pvc.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- route.yaml
- buckets.yaml